;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname project01) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(define (item-total price quantity)
  (* price quantity))
(define (discount-amount total discount-rate)
  (* total discount-rate))
(define (final-price total discount-rate)
  (- total(discount-amount total discount-rate)))
(define (tax-amount price tax-rate)
  (* price tax-rate))
(define (price-per-item total quantity)
  (/ total quantity))
(define (total-for-two-products price1 quantity1 price2 quantity2)
  (+ (item-total price1 quantity1)
     (item-total price2 quantity2)))
(item-total 1000 5)
(discount-amount 5000 0.10)
(final-price 5000 0.1)
(tax-amount 5000 0.1)
(price-per-item 5000 5)
(total-for-two-products 1000 2 1000 3)